[phases.setup]
nixPkgs = ["libsodium", "python312Full", "ffmpeg"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = "/opt/venv/bin/python bot.py"
